### ISSUE TITLE
Tab alternation should move on to the next node when completion is unambiguous

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#10]
Syntax:

``add client name STRING``

```
ad
<tab>
add
<tab>
ad
```

If there's only one possibility for completion then it should move on to the next node
```
ad
<tab>
add 
<tab>
add client
```

**Comment by alandekok** [comment]
Hmm... that's probably a linenoise thing.  It's a bit harder to track down

**Comment by arr2036** [comment]
Might also be worth syncing with current linenoise or even pulling it in a submodule.  Looks like the guy continued to develop it after you forked.
