### ISSUE TITLE
Tabbing skips through variables when a fixed alternative is allowed

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#14]
```
show session apn 
<tab>
show session apn all
```

Should refuse to tab complete as the next command is ambiguous

**Comment by alandekok** [comment]
what's the syntax?

It should probably refuse to allow syntaxes which are ambiguous:

    name STRING
    name all

the first one will always match, and it will never parse the "all" syntax.

**Comment by alandekok** [comment]
It now tabs through variables.  It shows INTEGER as a completion when an INTEGER is allowed at this point in the command sequence.  That's not perfect, as the user has to delete INTEGER and type in a real number.  But it at least shows what's available
