### ISSUE TITLE
Command history no longer works

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#15]
Probably still not reading from the right file.

Needs to write to ``~/.<file>`` too.

**Comment by alandekok** [comment]
It's reading from foo_history.txt.  Commit 81588bd63 makes it load / save history only if the input is a TTY.  So running recli with input from a file no longer updates the history.

It should put it's history into `$(HOME)/.recli/foo_history`  If it can run as multiple commands for the same user, it's probably best to avoid polluting `$(HOME)` with tons of `foo_history` files

**Comment by alandekok** [comment]
This should be fine now.
