### ISSUE TITLE
Repetition syntax

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#26]
I'm not sure how difficult this would be,  but it would be required if we wanted to wrap bucardo's control utility.

When you specify syncs you have certain arguments that are repeated:

```
bucardo add dbgroup radius_data_a madison_master:source lithia_master:source lithia_slave1:target lithia_slave2:target
```

The recli equivalent would be
```
add bucardo dbgroup radius_data_a source madison_master source madison_master target lithia_slave1 target lithia_slave2
```

So we'd need the syntax to be something like:

```
add bucardo dbgroup STRING (source STRING|target STRING)*
```

If the syntax tree wouldn't mind being a graph at times I imagine it'd be pretty simple,  but the code may make assumptions about syntax being acyclic and get stuck in infinite loops.

**Comment by alandekok** [comment]
It doesn't do `*` right now, only `+`.  But it shouldn't be difficult to add.

Right now, you can do `add bucardo dbgroup STRING ...` which is variable arguments.  There will no syntax checking, but it's something.

The internal representation of the syntax is high level.  It's not a DAG, but a AST.  So adding a `*` node is probably not difficult.
