### ISSUE TITLE
Readline history records partial commands

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#3]
When entering a context readline only records the partial commands

```text
recli> show session
recli ...> apn
```

In the above command sequence, readline will record:

```text
show session
apn
```

It should record

```text
show session
show session apn
```

Recli should then be modified to be smart enough to trim the amount of command matching the current context.

With the current behaviour,  if you execute commands within a context, exit, and re run recli, the command history isn't useful, unless you re-enter the same context.

**Comment by alandekok** [comment]
That's how readline works, unfortunately.  It records the text entered by the user.  It doesn't record any additional context.

If the history is recorded, it should also record the "start context" command.   i.e. user enters:

    show session
    apn

and those *exact* commands are recorded.  Should it record instead...

    show session
    show session apn

? and then "trim" the second command?  What if the `show session` command had a subcommand which was also `show session`?  What happens then?

The best solution is to not "be smart" about these things.  It records what the user enters.  As-is.  Then puts that into the history.  And it can then re-run the history.

Mangling user input is a bad idea.

**Comment by arr2036** [comment]
```? and then "trim" the second command? What if the show session command had a subcommand which was also show session? What happens then?```

Then it's fine, because the history would be:
```show session show session`` and only the first instance would be trimmed

It's only an issue if you're inconsistent with recording prefix + command.

As it is, the history is pretty useless.  The idea with history is to be able to press up and hit enter and it just work, at the moment, if you restart recli, it doesn't...
