### ISSUE TITLE
Wrong message for invalid format

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#30]
```
add client name foo ip 127.0.0.1 secret foo
                       ^ No matching command.
```

Should be something like ``Incorrect format for IPPREFIX``

IPPREFIX needs a trailing ``/<cidr>``

**Comment by alandekok** [comment]
The current code prints "Input does not match required syntax".  The datatypes callbacks have to be updated for any better error message to occur.

**Comment by arr2036** [comment]
That static message would be fine,  but for the above command I get 'No matching command'.
