### ISSUE TITLE
Weird syntax validation issue

### ISSUE THREAD

**Issue by arr2036** [alandekok/recli#5]
Syntax is

```text
show session mdn INTEGER active
show session mdn INTEGER
show session apn STRING count active
show session apn STRING count
show session apn STRING active
```

Command is
```text
recli> show session apn foo active
show session apn foo active
^ - Invalid input
```

```text
show session ((apn STRING count|mdn INTEGER) [active]|apn STRING active)
```

Removing any of the commands in the above syntax list seems to fix the issue.

**Comment by alandekok** [comment]
I've pushed a fix.

**Comment by arr2036** [comment]
It's worse now, it refuses commands that worked before.

``
update subscriber id INTEGER ip STRING
update subscriber id INTEGER ip none
show session mdn INTEGER
show session mdn INTEGER active
show session apn STRING [count] [active]
show session apn STRING [count]
show session apn STRING [active]
show session apn STRING
show subscriber username STRING
show subscriber mdn INTEGER
show subscriber ip IPADDR
show subscriber id INTEGER
show subscriber id all
```

none of the show subscriber commands work

**Comment by arr2036** [comment]
All with the same validation error with the marker at 0

**Comment by arr2036** [comment]
Removing the show session syntax allows show subscriber to work.

**Comment by arr2036** [comment]
Looking good:

```
nm-subscriber> ?
add subscriber mdn INTEGER username STRING password STRING [static-ip IPADDR]
delete subscriber id INTEGER
rehash
show (session (apn STRING [([active]|[count])]|(apn STRING [count]|mdn INTEGER) [active])|subscriber id INTEGER)
update subscriber id INTEGER (ip (IPADDR|none)|mdn INTEGER|password STRING|username STRING)
```
